[project]
name = "vision"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "groq>=0.24.0",
    "ncnn>=1.0.20250503",
    "pyaudio>=0.2.14",
]
